version: '3.8'
services:

  db:
    container_name: postgresql_container
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5435:5432'
    env_file:
      - .env
    networks:
      - bewise

  backend:
    container_name: quiz_app
    image: quiz_backend:latest
    restart: always
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
    ports:
      - '8000:8000'
    env_file:
      - .env
    networks:
      - bewise


volumes:
  postgres_data:

networks:
  bewise:
    driver: bridge