version: '3.8'
services:

  db:
    container_name: postgresql_container
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5435:5432'
    env_file:
      - .env_non_dev
    networks:
      - castom

  backend:
    container_name: quiz_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: sh -c "alembic upgrade head && gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    depends_on:
      - db
    ports:
      - '8000:8000'
    env_file:
      - .env_non_dev
    networks:
      - castom


volumes:
  postgres_data:

networks:
  castom:
    driver: bridge