"""Column answer type str

Revision ID: 00441272b700
Revises: 0d638a26489e
Create Date: 2023-05-24 15:55:58.582639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00441272b700'
down_revision = '0d638a26489e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
